// <auto-generated />
namespace Longhorn_Music_Team_17.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class customerSeed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(customerSeed));
        
        string IMigrationMetadata.Id
        {
            get { return "201611230739135_customerSeed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
